#
# This file contains configuration flags to customize your site
#

# Site Title
title: Jekyll Material Lite

description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# Your website URL (e.g. http://<username>.github.io or http://yourdomain.com)
# Used for Sitemap.xml and your RSS feed
url: http://mudpuddle.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
<<<<<<< HEAD
baseurl:
=======
baseurl: /jekyll-mdl
>>>>>>> gh-pages

# Contact/Social Info
email: your-email@domain.com
# https://twitter.com/<twitter_username>
twitter_username: jekyllrb
# https://github.com/<github_username>
github_username:  jekyll
# https://www.linkedin.com/in/<linkedin_username>
linkedin_username:
#https://www.facebook.com/<facebook_profile>
facebook_profile:
# https://plus.google.com/u/0/<gplus_profile>
gplus_profile:
# https://instagram.com/<instagram_username>
instagram_username:
# https://www.pinterest.com/pintrest_username
pintrest_username:


# Build settings
markdown: kramdown
